level_5/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
#    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('user_login/', views.user_login, name='user_login'),
]

level_5/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('basic_app.urls')),
]

level_5/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)
    
    def __str__(self):
        return self.user.username
    

level_5/basic_app/forms.py
from django import forms 
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level_5/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse("Your are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False 
    
    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()
            
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)   
            
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'basic_app/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})     


def user_login(request):
    
    if request.method == "POST":
        username - request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password= password)
        
        if user:
            if user.is_active:
                login(request, user)
                
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
            
        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print("USERNAME : {} and password {}".format(username, password))
            return HttpResponse("INVALID LOGIN DETAILS")
            
        
    else:
        return render(request, 'basic_app/login.html', {})

level_5/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:register' %}">REGISTER</a></li>

                {% if user.is_autheticated %}

                <li><a class="navbar-link" href="{% url 'basic_app:logout' %}">LOGOUT</a></li>

                {% else %}

                <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">LOGIN</a></li>

                {% endif %}



            </ul>
        </div>

    </nav>
<div class="container">

    {% block content %}

    {% endblock %}

</div>
    


    
</body>
</html>

level_5/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block content %}

<div class="jumbotron">
    <h1>DJANGO LEVEL 5</h1>
</div>

{% endblock %}

level_5/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}


{% block content %}

<div class="jumbotron">
    <p1>Please Login</p1>
    <form action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %}

        <label for="username">USERNAME</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">PASSWORD</label>
        <input type="password" name="password">

        <input type="submit" name="" value="login">

    </form>
</div>

{% endblock %}

level_5/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% load static %}

{% block content %}

<div class="jumbotron">
    {% if registered %}
    <h1>THANK YOu FOR REGISTR</h1>

    {% else %}

    <h1>Register Here</h1>
    <h3>FILL OUT THE FORM</h3>

    <form enctype="multipart/form-data" method="POST" >
        {% csrf_token %}

        {{ user_form.as_p}}

        {{ profile_form.as_p }}

        <input type="submit" name="" value="register">
    </form>

    {% endif %}
</div>

{% endblock %}